"""empty message

Revision ID: 0c8f840f8ce0
Revises: e7cd422654d5
Create Date: 2021-11-25 12:46:19.618801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8f840f8ce0'
down_revision = 'e7cd422654d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'product_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_key', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
