"""empty message

Revision ID: 73f144d209ee
Revises: 0c8f840f8ce0
Create Date: 2021-11-25 12:47:20.810438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f144d209ee'
down_revision = '0c8f840f8ce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'product_key')
    # ### end Alembic commands ###
