"""empty message

Revision ID: e7cd422654d5
Revises: c29481340f9d
Create Date: 2021-11-25 12:31:43.638775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7cd422654d5'
down_revision = 'c29481340f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_product_key_fkey', 'cart', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('cart_product_key_fkey', 'cart', 'product', ['product_key'], ['id'])
    # ### end Alembic commands ###
